import Head from 'next/head';
import Image from 'next/image';
import styles from '../../styles/Home.module.css';
import React from 'react';
import {Button, Col, Row} from 'antd';
import Techstack from '../components/Techstack';
import {
    fetchAllUserRepos,
    fetchNameData, fetchYmlDataForRepos,
} from '../integration/github';
import Repo from "../components/Repo";

export async function getServerSideProps() {
    try {
        const apiKey = process.env.REACT_APP_API_KEY;

        const username = 'AndrisP11';
        const ymlFilename = 'portfolio.yml'
        const dataName = await fetchNameData(username, apiKey);

        const repo = await fetchAllUserRepos(username, apiKey)

        const ymlFirstData = await fetchYmlDataForRepos(username, repo, ymlFilename, apiKey);

        return {
            props: {
                name: dataName.name,
                htmlUrl: dataName.html_url,
                bio: dataName.bio,
                avatarUrl: dataName.avatar_url,
                ymlFirstData,

            },
        };
    } catch (error) {
        return {
            props: {
                error: 'An error occurred while fetching the contribution data',
            },
        };
    }
}


interface Props {
    name: string;
    htmlUrl: string;
    bio: string;
    avatarUrl: string;
    ymlFirstData: { title: string, description: string, project_url: string, repo: string, owner: string, image_list: string[] }[];


}

export default function Home(props: Props) {

    return (
        <>
            <Head>
                <title>{props.name}</title>
                <meta name="description" content="Generated by create next app"/>
                <link rel="icon" href="/Portfolio/portfolio/public/favicon.ico"/>
            </Head>

            <main className={styles.main}>
                <img src={props.avatarUrl} alt='example' width="180" height="180"/>
                <h1 className={styles.title}>
                    {props.name}
                </h1>
                <h1>
                    <Techstack/>
                </h1>


                <p className={styles.description}>
                    {props.bio}{' '}

                    <Button type="primary" href={props.htmlUrl}>gitHub</Button>
                </p>
                <div className="site-card-wrapper">
                    <Row align='middle' justify='space-between' gutter={16}>
                        <Col xs={24} sm={12} md={8} lg={6} style={{marginBottom: '32px'}}>
                            {props.ymlFirstData && props.ymlFirstData.length > 0 && (
                                <Repo repoTitle={props.ymlFirstData[0].title}
                                      repoDescription={props.ymlFirstData[0].description}
                                      repoProjectUrl={props.ymlFirstData[0].project_url}
                                      repoName={props.ymlFirstData[0].repo} repoOwner={props.ymlFirstData[0].owner}
                                      repoImageList={props.ymlFirstData[0].image_list}/>
                            )}
                        </Col>
                        <Col xs={24} sm={12} md={8} lg={6} style={{marginBottom: '32px'}}>
                            {props.ymlFirstData && props.ymlFirstData.length > 0 && (
                                <Repo repoTitle={props.ymlFirstData[1].title}
                                      repoDescription={props.ymlFirstData[1].description}
                                      repoProjectUrl={props.ymlFirstData[1].project_url}
                                      repoName={props.ymlFirstData[1].repo} repoOwner={props.ymlFirstData[1].owner}
                                      repoImageList={props.ymlFirstData[1].image_list}/>
                            )}
                        </Col>
                        <Col xs={24} sm={12} md={8} lg={6} style={{marginBottom: '32px'}}>
                            {props.ymlFirstData && props.ymlFirstData.length > 0 && (
                                <Repo repoTitle={props.ymlFirstData[2].title}
                                      repoDescription={props.ymlFirstData[2].description}
                                      repoProjectUrl={props.ymlFirstData[2].project_url}
                                      repoName={props.ymlFirstData[2].repo} repoOwner={props.ymlFirstData[1].owner}
                                      repoImageList={props.ymlFirstData[2].image_list}/>
                            )}
                        </Col>
                        <Col xs={24} sm={12} md={8} lg={6} style={{marginBottom: '32px'}}>
                            {props.ymlFirstData && props.ymlFirstData.length > 0 && (
                                <Repo repoTitle={props.ymlFirstData[3].title}
                                      repoDescription={props.ymlFirstData[3].description}
                                      repoProjectUrl={props.ymlFirstData[3].project_url}
                                      repoName={props.ymlFirstData[3].repo} repoOwner={props.ymlFirstData[1].owner}
                                      repoImageList={props.ymlFirstData[3].image_list}/>
                            )}
                        </Col>
                    </Row>
                </div>

            </main>

            <footer className={styles.footer}>
                <a
                    href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
                    target="_blank"
                    rel="noopener noreferrer"
                >
                    Powered by{' '}
                    <span className={styles.logo}>
          <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16}/>
        </span>
                </a>
            </footer>
        </>
    );
}